# Generated by Django 5.0.6 on 2024-05-08 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventbooking',
            name='description',
            field=models.TextField(max_length=1500),
        ),
        migrations.AlterField(
            model_name='eventbooking',
            name='location',
            field=models.CharField(max_length=400, null=True),
        ),
    ]
