# Generated by Django 5.0.6 on 2024-05-08 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_eventbooking_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventbooking',
            name='start_time',
        ),
    ]
